version: 2

sources:
  - name: raw-data
    schema: sap_adw
    description: "Dados pré-processados, definidos de acordo com o Diagrama de Modelagem para criação das Tabelas Fato e Dimensão."
    tables:
      # Dimensão Endereço (Address)
      - name: address
      - name: countryregion
      - name: stateprovince
      # Dimensão Pagamento (Cartão de Crédito)        
      - name: creditcard
      # Dimensão Produto
      - name: product
      # Dimensão Cliente
      - name: customer
      - name: person
      - name: store
      # Dimensão Razão-Vendas (Pedidos)
      - name: salesorderheadersalesreason
      - name: salesreason
      # Fato Vendas      
      - name: salesorderdetail
      - name: salesorderheader